---
title: "STAT-5525  \n Homework Template"
subtitle: "Project 1"
author: "Ashley Ferraro & Emily Padula"
date: "July 5, 2024"
output:
  flexdashboard::flex_dashboard:
  orientation: rows
  social: menu
  source_code: embed

---
  



# Problem 1

## Part a

```{r}

# Import Libraries
library(haven)
library(ggplot2)
library(FNN)
library(dplyr)
library(plotly)
library(plyr)
library(GGally)
library(flexdashboard)

set.seed(145)

# Import file
dr2iff <- read_xpt("DR2IFF_I.xpt")
#summary(dr2iff)

```

```{r}

splitOccasion <- split(dr2iff, f=factor(dr2iff$DR2_030Z))
breakfastOccasion <- splitOccasion$"1"
lunchOccasion <- splitOccasion$"2"
dinnerOccasion <- splitOccasion$"3"
cleaned_dr2iff <- dr2iff[dr2iff$DR2_030Z <= 2, ]

```

### KNN Classification

## Text

```{r}

#DR2IGRMS
cleaned_dr2iff <- cleaned_dr2iff %>% filter(!is.na(DR2ISUGR) & !is.na(DR2ITFAT) & !is.na(DR2ICHOL) & !is.na(DR2_030Z) & !is.na(DR2IGRMS))

amount_80 <- nrow(cleaned_dr2iff) * 0.80

indexes <- seq_len(nrow(cleaned_dr2iff))

train_indexes <- sample(indexes, size=amount_80)

train_set_80 <- cleaned_dr2iff[train_indexes, ]
test_set_20  <- cleaned_dr2iff[-train_indexes, ]

train_features <- train_set_80[, c("DR2ICHOL","DR2IGRMS","DR2ISUGR","DR2ITFAT")]
test_features <- test_set_20[, c("DR2ICHOL","DR2IGRMS","DR2ISUGR","DR2ITFAT")]

train_classes <- train_set_80$DR2_030Z
test_classes <- test_set_20$DR2_030Z

knn_classes_output <- knn(train=train_features, test=test_features, cl=train_classes, k=5)

confusion_mat <- table("Predicted Classes" = knn_classes_output, "Actual Classes" = test_classes)

sum(knn_classes_output == test_classes) / length(test_classes)

print(cleaned_dr2iff$DR2_030Z)
print(knn_classes_output)

ggplot(test_set_20, aes(x=DR2ICHOL, y=DR2IGRMS, col=knn_classes_output)) + geom_point()

temp_test_set_20 <- test_set_20
temp_test_set_20$DR2_030Z <- as.factor(temp_test_set_20$DR2_030Z)

ggplot(temp_test_set_20, aes(x=DR2ICHOL, y=DR2IGRMS, col=DR2_030Z)) + geom_point()

```


```{r}


train_set_80 <- train_set_80[c("DR2IKCAL","DR2ICARB","DR2ISFAT","DR2IPFAT","DR2IPROT")]

test_set_20 <- test_set_20[c("DR2IKCAL","DR2ICARB","DR2ISFAT","DR2IPFAT","DR2IPROT")]

modfit <- lm(DR2IKCAL ~ ., data = train_set_80)

summary(modfit)

ggpairs(dr2iff, columns = c("DR2ICARB", "DR2ISFAT","DR2IPFAT", "DR2IKCAL", "DR2IPROT"))

MSE_tr_80 <- mean((train_set_80$DR2IKCAL - predict(modfit, newdata = train_set_80) )^2, na.rm = TRUE)

MSE_te_20 <- mean((test_set_20$DR2IKCAL - predict(modfit, newdata = test_set_20) )^2, na.rm = TRUE)

MSE_tr_80
MSE_te_20

```

