---
title: "Focal Chart (Top)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

Row {data-width=600}
-------------------------------------

### Text

The research question that we proposed for building the k-nearest neighbors (kNN) classification model, is the following question:

Is it possible to determine whether a person is consuming their meal at breakfast or lunch based on the carloic and nutrition values of that meal alone?
    
Row {data-width=600}
-------------------------------------

### Chart 1

```{r, fig.width=6, fig.height=4}

# Import Libraries
library(haven)
library(ggplot2)
library(FNN)
library(dplyr)
library(plotly)
library(plyr)
library(GGally)
library(flexdashboard)

set.seed(145)

# Import file
dr2iff <- read_xpt("DR2IFF_I.xpt")
#summary(dr2iff)

splitOccasion <- split(dr2iff, f=factor(dr2iff$DR2_030Z))
breakfastOccasion <- splitOccasion$"1"
lunchOccasion <- splitOccasion$"2"
dinnerOccasion <- splitOccasion$"3"
cleaned_dr2iff <- dr2iff[dr2iff$DR2_030Z <= 2, ]

cleaned_dr2iff <- cleaned_dr2iff %>% filter(!is.na(DR2ISUGR) & !is.na(DR2ITFAT) & !is.na(DR2ICHOL) & !is.na(DR2_030Z) & !is.na(DR2IGRMS))

amount_80 <- nrow(cleaned_dr2iff) * 0.80

indexes <- seq_len(nrow(cleaned_dr2iff))

train_indexes <- sample(indexes, size=amount_80)

train_set_80 <- cleaned_dr2iff[train_indexes, ]
test_set_20  <- cleaned_dr2iff[-train_indexes, ]

train_features <- train_set_80[, c("DR2ICHOL","DR2IGRMS","DR2ISUGR","DR2ITFAT")]
test_features <- test_set_20[, c("DR2ICHOL","DR2IGRMS","DR2ISUGR","DR2ITFAT")]

train_classes <- train_set_80$DR2_030Z
test_classes <- test_set_20$DR2_030Z

knn_classes_output <- knn(train=train_features, test=test_features, cl=train_classes, k=5)

confusion_mat <- table("Predicted Classes" = knn_classes_output, "Actual Classes" = test_classes)

#sum(knn_classes_output == test_classes) / length(test_classes)

#ggplot(test_set_20, aes(x=DR2ICHOL, y=DR2IGRMS, col=knn_classes_output)) + geom_point() + xlim(0, 1000) + ylim(0, 1000) + labs(col = "New Legend Name")

ggplot(test_set_20, aes(x=DR2ICHOL, y=DR2IGRMS, col=knn_classes_output)) + geom_point() + xlim(0, 1000) + ylim(0, 1000) + scale_color_discrete(
    name = "Predict Class",
    labels = c("Breakfast", "Lunch") # New legend values
  )


```

Row {data-width=600}
-------------------------------------

### Chart 1

```{r, fig.width=6, fig.height=4}
temp_test_set_20 <- test_set_20
temp_test_set_20$DR2_030Z <- as.factor(temp_test_set_20$DR2_030Z)

ggplot(temp_test_set_20, aes(x=DR2ICHOL, y=DR2IGRMS, col=DR2_030Z)) + geom_point() + xlim(0, 1000) + ylim(0, 1000) + scale_color_discrete(
    name = "Actual  Class",
    labels = c("Breakfast", "Lunch")) # New legend values
```

Row {data-height=350}
-------------------------------------
   
### Chart 2

```{r}
```   
    
### Chart 3

```{r}
```
